### ISSUE TITLE
Use of multiprocessing

### ISSUE THREAD

**Issue by ea-g** [helme/ecg_ptbxl_benchmarking#15]
I've noticed that whenever `multiprocessing.Pool()` is called, the **number of processes** is usually specified in your code, however considering that people have different rigs it will be better to leave it empty or equal to `os.cpu_count()` with either:

``` python
pool = multiprocessing.Pool()

# or this one when using "n_jobs" such as in scp_experiment.py
n_jobs = os.cpu_count()
pool = multiprocessing.Pool(n_jobs)
```

Additionally, in **wavelet.py** the pool is *never closed* in the `get_ecg_features()` function which causes some problems. 

Best,
Eric

**Comment by helme** [comment]
Hi @ea-g ,

thank you very much for pointing this out! I think you are right, using `os.cpu_count()` is more general. And closing the pool should be done in any case, sorry for any inconvenience! 

You can create a PR for this if you want to get this done soon, otherwise I will fix this in the next days/weeks.

Best,
helme

**Comment by Zbalabal** [comment]
What is the version of python please?
