### ISSUE TITLE
Filtering sparsely populated classes

### ISSUE THREAD

**Issue by Priya2698** [helme/ecg_ptbxl_benchmarking#16]
From the paper it seemed that all the classes have been included:  "We deliberately decided not to exclude sparsely populated classes from the evaluation". However, the README here mentions: "In all cases we restrict to classes with more than 50 entries in the whole dataset".

Could you clarify whether the metrics reported here consider all the classes or removes classes with less than 50 samples?

Best,
Priya

**Comment by helme** [comment]
Dear Priya,

thank you for pointing out this mistake. For the results in our leaderboard and in our paper we didn't constrained the classes as described in the README. Unfortunately this was still in the README by accident (since at some point of development we constrained classes to focus more on classes with many samples). I changed the README by deleting this sentence to avoid confusions. 

Best,
Patrick
