### ISSUE TITLE
ICBEB preprocess throws error

### ISSUE THREAD

**Issue by ramzan-basheer** [helme/ecg_ptbxl_benchmarking#28]
The line 'data = np.array([signal for signal, meta in data])' in load_raw_data_icbeb function throws error ---->ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6877,) + inhomogeneous part.

I checked the shape of the data list and they are different for each signal. Can i pad zeros to make all the shapes equal so that the numpy array to be created is consistent?

**Comment by helme** [comment]
Hi @ramzan-basheer , I'm not sure what's the issue here, but at the time we computed the dataset, default was `dtype=object` for  numpy for arrays. We haven't encountered any issues while training the models, since we randomly crop segments of the signals ensuring same length for each sample in the batch. Maybe, this answers your question.

If not, we do not recommend padding with zeros, but instead we recommend cropping to same size samples. 

I will close this issues for now, if you still encounter troubles, just re-open and ask again.

Best,
Patrick
