### ISSUE TITLE
Found conflicts! Looking for incompatible packages. error

### ISSUE THREAD

**Issue by yvzkbln** [helme/ecg_ptbxl_benchmarking#4]
When I run the "conda env create -f ecg_env.yml " command I get the following error.
Found conflicts! Looking for incompatible packages.

**Comment by BraINstinct0** [comment]
same issue.

**Comment by nstrodt** [comment]
Sorry for the late response. You are right, the provided yml does not seem to work anymore (which is strange since conda should in principle avoid these kinds of conflicts). We try to set up a new conda environment soon- hopefully towards the end of this week.

**Comment by rsaite** [comment]
For me, the conflict was caused by the requirement `  - dataclasses=0.6=py_0`. What worked for me was
1. Removing the dataclasses requirement from `ecg_env.yml `
2. Running `conda env create -f ecg_env.yml` and activating the environment
3. Installing dataclasses package with conda (yielding dataclasses 0.7 with automatic version selection)

**Comment by helme** [comment]
@rsaite thanks for pointing this out, currently I'm investigating the conda environment, I'll commit a updated yml file soon.

**Comment by helme** [comment]
Hi, I updated the conda environment with the minimal setup with wfdb, pytorch, torchvision, cudatoolkit, fastai, fastprogress. In addition I removed the prefix-line, header ids and the environment name. I hope this will fix your issues, just re-open the issue if this is not the case :)
