### ISSUE TITLE
I getting this error

### ISSUE THREAD

**Issue by yvzkbln** [helme/ecg_ptbxl_benchmarking#6]
OSError: Failed to interpret file '../data/ptbxl/raw100.npy' as a pickle

**Comment by helme** [comment]
Hi @yvzkbln , not sure what's the problem there, can you provide. Have you checked if the file exists indeed? i.e. have you aleady downloaded and preprocessed data via the provided bash-script `get_datasets.sh`?

**Comment by helme** [comment]
maybe something went wrong calling `get_datasets.sh`? Check if `data/ptbxl/raw100.npy` exist and is not broken (i.e. size of 0 bytes). In case of broken file, just delete and call again to see if something went wrong.

**Comment by yvzkbln** [comment]
As you mentioned, with the get_datasets command, all other files are created correctly, but the raw100 file is not created. Then when I run the reproduce_results code, it is created in 0 byte size and I get the error I mentioned above.
The raw100.npy and raw500.npy files cannot be downloaded with get_datasets.sh. Can you share these files with me so that I can download it?

**Comment by helme** [comment]
Hi @yvzkbln,

you will get this error while trying to load raw100.npy, but for the initial run this file needs to be created and dumped as pickle file. So I guess you get this error in the second run. Which error do you get in the first run? Because for raw500.npy there was an issue of files greater than 4GB which was resolved with the latest commit. But I'm not aware that this issue caused problem for raw100.npy (smaller than 4GB).

**Comment by yvzkbln** [comment]
In the first error, the output was `Killed`. The raw100.py is created in 0 byte size. The raw500.py is not created. Can you upload these files, please? I think this is a memory problem.

**Comment by helme** [comment]
Hi @yvzkbln,
unfortunately we can't provide this file, since we do not want to undermine Physionet as original source and therefore do not want to share the original data in any other way. I hope you will manage to generate the data by yourself. If you lacking memory, you should upgrade anyways for further analysis.
